// @ts-check

// TODO: Get these programmatically

/**
 * @typedef {"next" | "express" | "sveltekit"} SupportedFramework
 */

export const frameworks = {
  next: {
    name: "Next.js",
    src: "https://github.com/nextauthjs/next-auth-example",
    demo: "https://next-auth-example.vercel.app",
    envFile: ".env.local",
  },
  sveltekit: {
    name: "SvelteKit",
    src: "https://github.com/nextauthjs/sveltekit-auth-example",
    demo: "https://sveltekit-auth-example.vercel.app",
    envFile: ".env",
  },
  express: {
    name: "Express",
    src: "https://github.com/nextauthjs/express-auth-example",
    demo: "https://express-auth-example.vercel.app",
    envFile: ".env",
  },
}

export const providers = {
  "42-school": "42 School",
  apple: "Apple",
  asgardeo: "Asgardeo",
  auth0: "Auth0",
  authentik: "Authentik",
  "azure-ad-b2c": "Azure AD B2C",
  "azure-ad": "Azure AD",
  "azure-devops": "Azure DevOps",
  battlenet: "Battlenet",
  beyondidentity: "Beyond Identity",
  box: "Box",
  "boxyhq-saml": "Boxyhq SAML",
  bungie: "Bungie",
  "click-up": "Click-up",
  cognito: "Cognito",
  coinbase: "Coinbase",
  credentials: "Credentials",
  descope: "Descope",
  discord: "Discord",
  dribbble: "Dribbble",
  dropbox: "Dropbox",
  "duende-identity-server6": "Duende Identity Server 6",
  email: "Email",
  eveonline: "Eveonline",
  facebook: "Facebook",
  faceit: "Faceit",
  foursquare: "Foursquare",
  freshbooks: "Freshbooks",
  fusionauth: "FusionAuth",
  github: "GitHub",
  gitlab: "GitLab",
  google: "Google",
  hubspot: "Hubspot",
  "identity-server4": "Identity Server 4",
  instagram: "Instagram",
  kakao: "Kakao",
  keycloak: "Keycloak",
  line: "Line",
  linkedin: "LinkedIn",
  mailchimp: "Mailchimp",
  mailru: "Mail.ru",
  mastodon: "Mastodon",
  mattermost: "Mattermost",
  medium: "Medium",
  "microsoft-entra-id": "Microsoft Entra ID",
  naver: "Naver",
  netlify: "Netlify",
  netsuite: "Netsuite",
  nodemailer: "Nodemailer",
  notion: "Notion",
  okta: "Okta",
  onelogin: "Onelogin",
  "ory-hydra": "Ory Hydra",
  osso: "Osso",
  osu: "Osu",
  passage: "Passage",
  passkey: "Passkey",
  patreon: "Patreon",
  pinterest: "Pinterest",
  pipedrive: "Pipedrive",
  postmark: "Postmark",
  reddit: "Reddit",
  resend: "Resend",
  salesforce: "Salesforce",
  sendgrid: "Sendgrid",
  slack: "Slack",
  spotify: "Spotify",
  strava: "Strava",
  tiktok: "Tiktok",
  todoist: "Todoist",
  trakt: "Trakt",
  twitch: "Twitch",
  twitter: "Twitter",
  "united-effects": "United Effects",
  vk: "Vk",
  webex: "Webex",
  wikimedia: "Wikimedia",
  wordpress: "Wordpress",
  workos: "WorkOS",
  yandex: "Yandex",
  zitadel: "Zitadel",
  zoho: "Zoho",
  zoom: "Zoom",
}

export const adapters = {
  none: "None",
  "adapter-azure-tables": "Azure Tables",
  d1: "d1",
  dgraph: "Dgraph",
  drizzle: "Drizzle",
  dynamodb: "DynamoDB",
  edgedb: "EdgeDB",
  fauna: "Fauna",
  firebase: "Firebase",
  hasura: "Hasura",
  kysely: "Kysely",
  "mikro-orm": "MikroORM",
  mongodb: "MongoDB",
  neo4j: "Neo4j",
  pg: "PostgreSQL",
  pouchdb: "PouchDB",
  prisma: "Prisma",
  sequelize: "Sequelize",
  supabase: "Supabase",
  surrealdb: "SurrealDB",
  typeorm: "TypeORM",
  unstorage: "Unstorage",
  "upstash-redis": "Upstash Redis",
  xata: "Xata",
}
